spring.application.name=ecommerce-backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SvVRHwVyrFghse}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:vLiiF7TGjlPm1ifLV8qAal7e}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dogmybj79}
cloudinary.api-key=${CLOUDINARY_API_KEY:992154917459457}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:a4o-6Qw0YztaHdFxPGnfskZKPMI}

jwt.secret=${JWT_SECRET:your-secret-key-change-in-production}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
